name       : group-service
version    : 1.3.0
release    : 3
source     :
    - https://github.com/zhuyaliang/group-service/archive/refs/tags/1.3.0.tar.gz : 4ae8be84b90ebf350f24a2bddfa0ac2a167c42304ba0bae4260ad516066157b1
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : Borrowing DBUS services to manage user groups
description: |
    Borrowing DBUS services to manage user groups.
setup      : |
    %meson_configure --sysconfdir=/usr/share -Dsystemd=true
build      : |
    %ninja_build
install    : |
    %ninja_install
