name       : group-service
version    : 1.2.0
release    : 1
source     :
    - git|https://github.com/zhuyaliang/group-service.git : 9063c7989c669f17cdc6ef1b0ef565801771b7e6
license    : GPL-3.0-or-later
component  : desktop.mate
summary    : Borrowing DBUS services to manage user groups
description: |
    Borrowing DBUS services to manage user groups.
setup      : |
    %meson_configure -Dsystemd=true
build      : |
    %ninja_build
install    : |
    %ninja_install
